[theme]
# Primary accent color for interactive elements.
primaryColor = "#EF7840"

# Background color for the main content area.
backgroundColor = "#F5F5F7"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#afc8e6"

# Color used for almost all text.
textColor = "#000000"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
